### ISSUE TITLE
Sorry my bad China lang

### ISSUE THREAD

**Issue by Mepth** [ZeroDream-CN/PHPMC7#1]
您好，我将您的项目翻译成俄语，但我不明白图片中的内容。https://camo.githubusercontent.com/979ba0dac1bee1580095a84a218cf42043473bc2/68747470733a2f2f692e6e61746672702e6f72672f39303635326162323735636539343263373166303065623235303130343232352e706e67

链接到翻译：https：//github.com/maxim19116/PHPMC7

**Comment by Zxilly** [comment]
It means

Minecraft Server Manager
OpenSource | Cross Platform | Distributed | Group Support

**Comment by kasuganosoras** [comment]
Thank you for translation, PHPMC 7 support multi-language now.
Link: https://github.com/kasuganosoras/PHPMC7-Multi-Language
