### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by junxiesky** [ZeroDream-CN/PHPMC7#11]
**简单描述 bug**
打开网页后无法安装

**如何复现**
以下是让 bug 复现的方法：
1. 按照mcbbs教程进行安装

**你所期望的结果**
在网页端可以安装

**屏幕截图**
如果可以，请提供屏幕截图，以便我们更好的分析

**操作系统（您所使用的操作系统）：**
 - 客户端系统：Android
 - 服务器系统：Ubuntu18
 - 客户端浏览器：Chrome
 - 浏览器版本：84

**附加内容**
任何您认为有助于我们分析问题的附加内容

**Comment by junxiesky** [comment]
![Screenshot_2020-05-05-21-50-58](https://user-images.githubusercontent.com/30452768/81073829-c8dbef80-8f1a-11ea-8158-537eee938dda.png)

**Comment by junxiesky** [comment]
![Screenshot_2020-05-05-22-01-40](https://user-images.githubusercontent.com/30452768/81074742-05f4b180-8f1c-11ea-89c3-1536445ce4d5.png)

**Comment by junxiesky** [comment]
@kasuganosoras

**Comment by kasuganosoras** [comment]
请先手动创建数据库
另外请提供一下你的数据库软件版本

**Comment by junxiesky** [comment]
> 请先手动创建数据库
> 另外请提供一下你的数据库软件版本

不知道 我是apt自动安装的数据库

**Comment by junxiesky** [comment]
> 请先手动创建数据库
> 另外请提供一下你的数据库软件版本

我试试自己创建数据库

**Comment by junxiesky** [comment]
> 请先手动创建数据库
> 另外请提供一下你的数据库软件版本

问题解决了
