### ISSUE TITLE
能否自定义服务端版本

### ISSUE THREAD

**Issue by Zxilly** [ZeroDream-CN/PHPMC7#2]
**你所请求的功能和你的问题有关吗？**
是的

**描述你所需要的功能**
自定义服务端版本

**描述你曾考虑过的解决方案**
替换lib/PaperSpigot-1.8.8-R0.1-SNAPSHOT.jar

**附加信息**
无

**Comment by kasuganosoras** [comment]
这个是支持自定义服务端版本的，在服务端设置里修改启动参数，指定新的服务端名称就可以了。
