### ISSUE TITLE
按照mcbbs.net中的安装步骤在CentOS 7的VPS中部署PHPMC7，然而并没有出现安装界面

### ISSUE THREAD

**Issue by s-leeq** [ZeroDream-CN/PHPMC7#9]
在进行到教程中的1.8后尝试在浏览器中输入VPS的IP地址进行访问，但是显示的却是OneinStack的界面... 不知道我是不是在上传的时候将文件上传到了错误的位置  求解
<img width="1440" alt="截屏2019-12-30下午10 30 43" src="https://user-images.githubusercontent.com/43868433/71586136-1a7f0280-2b54-11ea-85b6-1b7d9d12b27b.png">
<img width="439" alt="截屏2019-12-30下午10 30 11" src="https://user-images.githubusercontent.com/43868433/71586137-1b179900-2b54-11ea-9fb3-52183ae932bf.png">

**Comment by s-leeq** [comment]
我是对照的这个教程: https://www.mcbbs.net/thread-819800-1-1.html

**Comment by kasuganosoras** [comment]
上传错位置了，你应该把文件夹内的所有文件放在 /data/wwwroot/default/ 里面，而不是整个文件夹放进去。

**Comment by s-leeq** [comment]
> 上传错位置了，你应该把文件夹内的所有文件放在 /data/wwwroot/default/ 里面，而不是整个文件夹放进去。

你好，我刚刚照着你所说的，将文件放到/data/wwwroot/default/中，但是貌似还是不太行...
<img width="1440" alt="截屏2020-02-01下午3 47 30" src="https://user-images.githubusercontent.com/43868433/73588964-a0eb8300-450a-11ea-9bfd-35c4bbbd9a87.png">
<img width="1233" alt="截屏2020-02-01下午3 45 24" src="https://user-images.githubusercontent.com/43868433/73588965-a1841980-450a-11ea-9894-24814ea5f38e.png">

**Comment by kasuganosoras** [comment]
请先把原目录中的所有文件删除以后再上传新的

**Comment by s-leeq** [comment]
你好，问题已解决，十分感谢你耐心的帮助！！
